server:  
  port: ${PORT:4446}

spring:  
  application:
    name: gps-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
      org.springframework.data.mongodb: DEBUG

  redis:
     database: 0
     host: 10.200.102.223
     port: 6379
     #    password:

#     pool:

  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: track


eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadataMap:
        version: ${VERSION:1}
        labelOr: ${LABELOR:test}


ribbon:
  eureka:
    enabled: true